### ISSUE TITLE
irods-rest-client-cpp service should depend on nginx-reverse-proxy

### ISSUE THREAD

**Issue by alanking** [irods/irods_demo#33]
nginx-reverse-proxy currently depends on irods-rest-client-cpp.

This should be reversed such that when the user runs:
```
docker-compose up irods-rest-client-cpp
```
...the nginx-reverse-proxy service comes up with it.

This makes more sense because the user will naturally want to start the REST client over the reverse proxy, but the reverse proxy is required to interact with the REST client as none of the REST client ports are exposed by default.

**Comment by trel** [comment]
also, the zmt requires the irods-rest-client-cpp, rather than the nginx-reverse-proxy

**Comment by trel** [comment]
Well, upon testing the flip to have irods-rest-client-cpp depend on nginx-reverse-proxy...

I hit the problem that the configuration of the nginx-reverse-proxy needs the docker networking to already exist for the host that is irods-rest-client-cpp.   So the existing dependency is correct for now... otherwise, the nginx-reverse-proxy container exits early with `1`.

And therefore, the ZMT tweak is also wrong.   It should continue to depend on the nginx-reverse-proxy.

Closing as resolved/invalid.
