### ISSUE TITLE
document launching on remote machine

### ISSUE THREAD

**Issue by scaleoutsean** [irods/irods_demo#39]
Maybe it's common knowledge for iRODS users but some info about passwords would be helpful (at least for the Web UI but if convenient for other main components as well).

In docker-compose output I see a number of places with passwords (NFS client, PostgreSQL, etc.), and while ipasswd recognizes `rods` as current iRODS password, in the PostgreSQL iRODS irods-ext database I see the password field is empty... It's a lot of work to figure it out.

I used `ipasswd` to change iRODS password in `irods_demo-irods-client-zmt` but that didn't seem to apply to the Web UI. A restart of docker-compose didn't help either.

**Comment by trel** [comment]
The irods_demo is a vanilla, out-of-the-box installation with only a default rodsadmin iRODS account created (with rods/rods as username/password).

If you change an iRODS password in the irods-catalog-provider (with `ipasswd`), any client that connects will be able to use that same account with the newly updated password.   A better plan may be to create a new user (alice, etc.) and test logging in with those to confirm your mental model.

The passwords set for PostgreSQL (both irods-catalog and metalnx-db) are the 'root' passwords for the database system itself.

And again, all of these are in plaintext in the config files because this is just a demo.   Please definitely do not use this for anything other than learning how the pieces fit together.

Hope that helps - this is very new... it definitely can be better.   Please leave bug reports when you find bugs.

Can you say more about this?
> I see the password field is empty

**Comment by korydraughn** [comment]
To add to what @trel said ...

Some of the services in the demo require an admin account to function properly. Those services use that account to proxy for all users interacting with the service.

For the demo, you should avoid changing the password of the `rods` account because other containers require that.

What you can do is create a new user and give them whatever password you want. You can do that by `docker exec`'ing into the icommands container and running the following:
```bash
iadmin mkuser <username> <user-type>
iadmin moduser <username> password <password>
```
- `<username>` is the name of the new user to create.
- `<user-type` is one of the following:
  - rodsuser: A non-admin user.
  - rodsadmin: A admin user just like the `rods` account.
  - groupadmin: A user type with limited admin privileges in regard to groups.
  - rodsgroup: Use if you want to create a group.
- `<password>` is the password to assign to the new user.

See https://docs.irods.org/4.3.0/icommands/administrator/#iadmin for more details.

**Comment by korydraughn** [comment]
Metalnx uses a private database (irods-ext) to cache various pieces of information. We're planning on removing that in the future.

The credentials for users will be stored in the ICAT database of the irods_catalog service.

> ... but can you tell me whether after adding an account as per above the account is supposed to be able to log in to the Web UI?

Yes. You should be able to log into the web apps after creating a new user. If you run into issues, please report those.

**Comment by scaleoutsean** [comment]
I figured that just minutes ago.. Not the fix, but the problem.

And then installed X-Windows on the box to work around it.

![image](https://user-images.githubusercontent.com/16622642/199512089-8de89561-64cc-4da0-ab39-051b961fcf11.png)

**Comment by trel** [comment]
Updating the REACT_APP_REST_API_URL should get you there.     Then you go to yourhostname:9000 and ZMT should render - no X-Windows necessary.

**Comment by trel** [comment]
i'll update the README with the REACT_APP_REST_API_URL hint.

**Comment by trel** [comment]
README updated - closing.
